interface Entity {
    id: ID!
    name: String!
    relations: [Entity!]! @relationship(type: "Relationship", properties: "Relationship")
}

type Person implements Entity {
    uname: String!
    email: String
}

type Relationship @relationshipProperties {
    type: RelationshipType 
}

enum RelationshipType {
    Family
    Friend
    Owner
    Employee
    Client
}