interface Entity {
    id: ID!
    name: String!
    relations: [Entity!]! @relationship(type: RelationshipType, properties: "Relationship")
}

type Person implements Entity {
    uname: String!
    email: String
}

type Relationship @relationshipProperties {
    type: RelationshipType,
    descriptor: string
}

enum RelationshipType {
    Family
    Friend
    Owner
    Employee
    Client
}